name: Test Backend on Pull Request

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches: 
      - main
      - staging

jobs:
  linter:
    name: Apply Ruff Linter to Backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          echo "Ruff Installed"
      - name: Apply Ruff Linter
        run: |
          ruff check --fix --show-fixes
          echo "Ruff linter check and fix applied" 
          ruff format .
          echo "File formatting applied"
      - name: Commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated code fixes and formatting by ruff"

  test:
    needs: linter
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Docker and Docker Compose
        run: |
          # Install Docker and Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

        
      - name: Run Tests in Docker Containers
        run: |
          bash ./run-tests.sh